# Generated by Django 4.2.2 on 2023-06-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplyoee',
            name='hire_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emplyoee',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emplyoee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
